"""Index expander — maps index names to lists of constituent company names.

Company names are intentionally matched to the slugs used by ATS providers,
so they may differ slightly from the official stock-exchange name.
Lists are hardcoded (no live API needed) and should be updated periodically.
"""

from __future__ import annotations

# fmt: off
_FTSE_100: tuple[str, ...] = (
    "3i",
    "Admiral",
    "Anglo American",
    "Antofagasta",
    "AstraZeneca",
    "Auto Trader",
    "Aviva",
    "BAE Systems",
    "Barclays",
    "Barratt Developments",
    "BHP",
    "BP",
    "British American Tobacco",
    "British Land",
    "BT",
    "Bunzl",
    "Burberry",
    "Centrica",
    "Coca-Cola HBC",
    "Compass Group",
    "CRH",
    "Croda International",
    "DCC",
    "Diageo",
    "easyJet",
    "Endeavour Mining",
    "Experian",
    "Flutter Entertainment",
    "Fresnillo",
    "GSK",
    "Haleon",
    "Halma",
    "Hikma Pharmaceuticals",
    "HSBC",
    "IMI",
    "Imperial Brands",
    "Informa",
    "Intermediate Capital Group",
    "Intertek",
    "JD Sports",
    "Kingfisher",
    "Land Securities",
    "Legal & General",
    "Lloyds Banking Group",
    "London Stock Exchange",
    "M&G",
    "Marks and Spencer",
    "Melrose Industries",
    "Mondi",
    "National Grid",
    "NatWest",
    "Next",
    "Ocado",
    "Pearson",
    "Persimmon",
    "Phoenix Group",
    "Prudential",
    "Reckitt",
    "Relx",
    "Rentokil Initial",
    "Rio Tinto",
    "Rolls-Royce",
    "RSA Insurance",
    "Sage",
    "Schroders",
    "SEGRO",
    "Severn Trent",
    "Shell",
    "Smith & Nephew",
    "Smiths Group",
    "Spirent Communications",
    "SSE",
    "Standard Chartered",
    "St James's Place",
    "Taylor Wimpey",
    "Tesco",
    "Unilever",
    "United Utilities",
    "Vodafone",
    "Whitbread",
    "WPP",
)

_FTSE_AIM_100: tuple[str, ...] = (
    "Abcam",
    "accesso Technology",
    "Alpha FMC",
    "AJ Bell",
    "Alphawave IP",
    "Ashtead Technology",
    "Benchmark Holdings",
    "Bytes Technology",
    "Calnex Solutions",
    "Caretech",
    "Clarkson",
    "CMC Markets",
    "Codemasters",
    "Corero Network Security",
    "CVS Group",
    "discoverIE",
    "dotdigital",
    "EKF Diagnostics",
    "EnSilica",
    "Ergomed",
    "EV Group",
    "FD Technologies",
    "Focusrite",
    "Games Workshop",
    "GB Group",
    "Gear4music",
    "Gresham Technologies",
    "Hargreaves Services",
    "Horizon Discovery",
    "IMImobile",
    "Inspired Energy",
    "Inspired PLC",
    "Jet2",
    "K3 Capital",
    "Keywords Studios",
    "Kinovo",
    "Loungers",
    "Macfarlane Group",
    "MainTel",
    "Mattioli Woods",
    "MaxCyte",
    "Mind Gym",
    "Moneysupermarket",
    "Naked Wines",
    "Nexus Infrastructure",
    "Norman Broadbent",
    "Norcros",
    "Norman Disney Young",
    "OnTheMarket",
    "Optibiotix Health",
    "Panther Securities",
    "Paragon Banking Group",
    "Pensana",
    "Porvair",
    "Premier Foods",
    "Pure Gold Mining",
    "Quartix Technologies",
    "Quiz",
    "Ramsdens Holdings",
    "Real Good Food",
    "Restore",
    "Rightmove",
    "Robert Walters",
    "RPS Group",
    "S4 Capital",
    "Sensata Technologies",
    "Shield Therapeutics",
    "Shoe Zone",
    "SimplyBiz",
    "Smart Metering Systems",
    "Somero Enterprises",
    "Spectral MD",
    "Spectroscopy",
    "SThree",
    "Sylvania Platinum",
    "Team17",
    "The Naked Wines",
    "Trifast",
    "Tristel",
    "Volex",
    "WANdisco",
    "Watkin Jones",
    "XPS Pensions",
    "YouGov",
    "Zotefoams",
)
# fmt: on

_INDEX_MAP: dict[str, tuple[str, ...]] = {
    "ftse100": _FTSE_100,
    "aim100": _FTSE_AIM_100,
}

KNOWN_INDICES: frozenset[str] = frozenset(_INDEX_MAP)


def companies_for_index(index_name: str) -> list[str]:
    """Return the list of company names for the given *index_name*.

    *index_name* is case-insensitive (``"FTSE100"`` and ``"ftse100"`` both work).
    Raises ``ValueError`` for unknown index names.
    """
    key = index_name.lower()
    if key not in _INDEX_MAP:
        raise ValueError(
            f"Unknown index '{index_name}'. "
            f"Available: {', '.join(sorted(KNOWN_INDICES))}"
        )
    return list(_INDEX_MAP[key])
